apiVersion: v1
kind: Service
metadata:
  name: offreandprestation-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 91
      targetPort: 8091
  selector:
    app: offreandprestation-service