apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
        - name: registry-service
          image: emilekmddev/spotlight:registry-service
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_APPLICATION_NAME
              value: "registry-service"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:8888"
            - name : SPRING_CONFIG_IMPORT
              value : "configserver:"