services:
  #Base de donnees Nosql
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chat_db

  #message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672" # Port standard AMQP (communication interne Spring)
      - "15672:15672" # Interface d'admin Web (http://localhost:15672)
      - "61613:61613" # Port STOMP (pour les WebSockets)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: /bin/bash -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"