server:
  port:8080

spring:
  application:
    name:chat-service

#Config MongoDB
data:
  mongodb:
    uri: mongodb://localhost:27017/chat_db
    auto-index-creation: true

#Config RabbitMq
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
