apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
          image: emilekmddev/spotlight:proxy-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "proxy-service"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"